# Generated by Django 5.0.6 on 2024-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=200)),
                ('bike', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='book',
            new_name='bookname',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='name',
        ),
    ]
