# Generated by Django 5.0.6 on 2024-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_showroom_rename_book_reader_bookname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
